content/post/mirror-help/anaconda.md

remove matsci since https://github.com/sjtug/mirror-docker/pull/29

remove matsci from help, and suggest not use free

---

content/post/mirror-help/anaconda.md

Please merge this after we finish sync of pytorch

mirror: add pytorch for anaconda

---

content/post/mirror-help/archlinuxarm.md

I added a brief help doc for archlinuxarm, PTAL @skyzh

Add help doc for archlinuxarm

---

content/post/mirror-help/ubuntu.md

(Revised from #34) Added guide for editing `sources.list` using `sed` command and provided a sample for edited list file.

Update mirror help for Ubuntu

---

content/post/mirror-help/emacs-elpa.md

fix https://github.com/sjtug/mirror-requests/issues/128

mirror-help: fix emacs-elpa

---

content/post/mirror-help/guix.md

mirror-help: Add guix.

---

content/post/mirror-help/linuxliteos.md

@hmsjy2017 是否应该编辑 `/etc/apt/sources.list`？能否帮忙确认一下？

mirror-help: update linuxliteos

---

content/post/mirror-help/dragonflybsd.md

See https://github.com/sjtug/mirror-requests/issues/137 for the new mirror request of dragonflybsd.

mirror-help: Add dragonflybsd

---

content/post/mirror-help/nix-channels.md

mirror-help: Add nix-channels

---

content/post/mirror-help/ohmyzsh.md

mirror-help: add ohmyzsh

---

content/post/mirror-help/openEuler.md

mirror-help: add openEuler

---

content/post/mirror-help/debian.md

mirror-help: update Debian

---

config.toml

hugo: allow unsafe HTML

---

content/post/mirror-help/docker-ce.md

mirror-help: update docker-ce.md

---

content/post/mirror-help/ubuntu-cloud-images.md

mirror-help:Update content/post/mirror-help/ubuntu-cloud-images.md

mirror-help: add ubuntu-cloud-images

---

content/post/mirror-help/ubuntu-cd

mirror-help:add ubuntu-cd.md
markdown新手 可能有问题 
顺带一提 好像镜像站并没有收录old release版本

mirror-help:add ubuntu-cd.md

---

content/post/mirror-help/ubuntu-cdimage.md

mirror-help:add ubuntu-cdimage.md

mirror-help:add ubuntu-cdimage.md

---

content/post/mirror-help/ubuntu-cd.md
content/post/mirror-help/ubuntu-cdimage.md

mirror-help:优化帮助文件的内链

---

content/post/mirror-help/debian-cd.md

mirror-help:add debian-cd.md

---

content/post/mirror-help/alpine.md

mirror-help: 更正 Alpine 替换源时存在的错误

---

content/post/mirror-help/fedora.md

Fix https://github.com/sjtug/portal/issues/120

mirror-help: update fedora

---

content/post/mirror-help/emacs-elpa.md

* Removed 3 obsolete sites.
* Updated melpa-stable URL.
* Use https for official sites.

Remove obsolete mirrors and update URLs

---

content/post/mirror-help/nix-channels.md

See also https://github.com/ustclug/mirrorhelp/pull/204.

mirror-help/nix-channels: add instructions for NixOS 22.05

---

content/post/mirror-help/crates.io.md

ref: https://github.com/sjtug/mirror-docker-unified/pull/358

mirror-help: crates.io sparse index

---

.github/workflows/build.yml
.github/workflows/deploy.yml
content/post/mirror-help/immortalwrt.md

Add OPKG setup instructions for the ImmortalWrt project.

mirror-help: add setup instructions for immortalwrt

---

content/post/mirror-help/docker-registry.md

Podman is an OCI-compatible container engine with FOSS licensing: https://podman.io/

add Podman instructions for docker-registry

---

content/post/mirror-help/leopardsh.md

mirror-help: add leopardsh.md

---

content/post/mirror-help/leopardsh.md

mirror-help: fix leopardsh.md

---

content/post/mirror-help/leopardsh.md

Support for mirrors with no HTTP and no HEAD support

mirror-help: Update leopardsh.md

---

content/post/mirror-help/ubuntu-ports.md
content/post/mirror-help/ubuntu.md

Closes sjtug/mirror-requests#378
Add support for new deb822 format for Ubuntu 24.04 and later
Fix a typo of Ubuntu 22.04 configuration in ubuntu.md
Ref: https://mirrors.tuna.tsinghua.edu.cn/help/ubuntu/

Update ubuntu.md, ubuntu-ports.md
